### ISSUE TITLE
Refactor Kubestone labels

### ISSUE THREAD

**Issue by otto-von-bivouac** [xridge/kubestone#112]
Currently, we are setting two labels in the created k8s resources: `kubestone-cr-name` and `app`. It would look much nicer if we would be consistent and use our FQDN: `kubestone.xridge.io/cr-name` and `kubestone.xridge.io/app`

**Comment by amitlevy21** [comment]
Hi! @otto-von-bivouac 
Can I work on it?

**Comment by otto-von-bivouac** [comment]
Hi @amitlevy21 !

Of course, and thanks for providing a helping hand, much appreciated. 
You can find our dev guide here: http://kubestone.io/en/latest/devguide/

Please let us know if you need any assistance.
