### ISSUE TITLE
Opportunity for collaboration

### ISSUE THREAD

**Issue by jtaleric** [xridge/kubestone#161]
hey! Sounds like we have pretty similar tools! We have built a tool called Ripsaw[1], which orchestrates different industry standard benchmarks, like pgbench, hammerdb, fio, uperf, etc. 

The other neat part of our work is that the benchmark results of said workloads are stored for future comparison (ie, run to run comparison). 

Let us know if there is any possibility to converge our efforts!

[1] https://github.com/cloud-bulldozer/ripsaw

**Comment by otto-von-bivouac** [comment]
Thanks for reaching out, we indeed are heading to the same direction!
Some of our yet-to-be-open-sourced parts are also covering result persistence & comparison,
from a slightly different angle.

I'll reach out to you shortly on kubernetes slack to bring the discussion further.

**Comment by jtaleric** [comment]
Hey Otto - Let me know a good time to catch up, I tried pinging you on Slack, but maybe here is better to chat?

**Comment by kalinon** [comment]
Def have some overlap here. ive been cranking out new benchmarks for kubestone. Perhaps a division of effort? One of the things needed (imo) was the storage and review of the benchmark data. Which looks like @jtaleric seems to be doing. Where kubestone is more focused currently on executing said benchmarks, perhaps ripsaw could be more focused on scheduling, recording, and comparing? or something along those lines, using kubestone as the executor.

**Comment by jtaleric** [comment]
> Def have some overlap here. ive been cranking out new benchmarks for **kubestone**. Perhaps a division of effort? One of the things needed (imo) was the storage and review of the benchmark data. Which looks like @jtaleric seems to be doing. Where **kubestone** is more focused currently on executing said benchmarks, perhaps **ripsaw** could be more focused on scheduling, recording, and comparing? or something along those lines, using **kubestone** as the executor.

Hey @kalinon, Agree on the overlap! However, I started this thread back in November 2019, and it was quickly closed... I haven't heard from @otto-von-bivouac, so I am not sure about the integration between Ripsaw and kubestone.

For some background on our direction, we are trying to keep distinct functions in their own project(s) under the **cloud-bulldozer** organization in github. For example, **Ripsaw** only orchestrates the workload, so as you point out, it is pretty simple in its functionality! However, Ripsaw is using another project within **cloud-bulldozer**, called **SNAFU**. 

**SNAFU** is a framework which can be used within both containerized and non-containerized environments. Allowing us within the Performance group reuse our automation across environments. This hasn't been done yet, but we could begin answering questions like, "What is the % difference between bare-metal, Openstack and kubernetes when running FIO with X jobfile."... 

Which takes me to **Touchstone** in **cloud-bulldozer**, since we are using **SNAFU** to actually execute the workload, parse the results and index into ES.. We know the data structures, so we can easily compare them, no matter the infrastructure. 

To ensure context when comparing results we have another project called **stockpile / backpack** which will capture detailed information (dmidecode, k8s info, etc) and index it into ES. This will provide the Performance engineer the necessary context, when comparing results. 

Sorry for the long reply... If we were to do some sort of integration, it could be having kubestone call SNAFU for the supported workloads we currently have there... Thoughts?

**Comment by kalinon** [comment]
@jtaleric very helpful information. I did not know of these tools. But it seems logical to be able to add SNAFU as a executor to Kubestone.

I was hoping to propose and add log parsing and storage to kubestone in the long run, for the exact comparisons you are mentioning. However i despise duplicated effort. There is definitely a overlap here, we just need to find the lines and maybe define them.

I love the idea of a more unified benchmarking tool such as SNAFU, but it may be impossible to "catch them all". Its goals and objectives also align with what Ive been doing lately, so i will need to take a look before i give too much of an opinionated response. 

👍
