### ISSUE TITLE
Problem running the installation of kubestone

### ISSUE THREAD

**Issue by famoussou** [xridge/kubestone#187]
The example at https://kubestone.io/en/latest/quickstart/#running-the-benchmark does not run as documented:

$ ./kustomize build github.com/xridge/kubestone/config/default?ref=v0.5.0 |sudo  kubectl create  -f -
namespace/system created
_**Warning**_: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/drills.perf.kubestone.xridge.io created
customresourcedefinition.apiextensions.k8s.io/fios.perf.kubestone.xridge.io created
customresourcedefinition.apiextensions.k8s.io/iopings.perf.kubestone.xridge.io created
customresourcedefinition.apiextensions.k8s.io/iperf3s.perf.kubestone.xridge.io created
customresourcedefinition.apiextensions.k8s.io/pgbenches.perf.kubestone.xridge.io created
customresourcedefinition.apiextensions.k8s.io/qperves.perf.kubestone.xridge.io created
customresourcedefinition.apiextensions.k8s.io/sysbenches.perf.kubestone.xridge.io created
clusterrole.rbac.authorization.k8s.io/kubestone-manager-role created
clusterrole.rbac.authorization.k8s.io/kubestone-proxy-role created
clusterrolebinding.rbac.authorization.k8s.io/kubestone-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/kubestone-proxy-rolebinding created
**Error from server (NotFound): error when creating "STDIN": namespaces "kubestone-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "kubestone-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "kubestone-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "kubestone-system" not found**

###  **Versions**

$ ./kustomize version
{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-08-29T17:44:01Z GoOs:linux GoArch:amd64}

$ sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tibkiss** [comment]
thanks for reporting this issue. There are some braking changes in kustomize, which needs to be addressed.
Until we fix, please try to do the steps from master:
```
$ git clone git@github.com:xridge/kubestone.git
$ cd kubestone
$ kubectl create -n kubestone-system
$ kustomize build config/default | kubectl create -f -
```
