### ISSUE TITLE
Fio: hostpath support

### ISSUE THREAD

**Issue by wgershwitz** [xridge/kubestone#88]
hostpath parameter is helpful to measure disk speed on the nodes. Fio should be extended to enhance our flexibility.

Further read: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath

**Comment by julio-santiesteban** [comment]
@wgershwitz Can you please elaborate further on this? What exactly would this `hostdir` parameter do?

**Comment by wgershwitz** [comment]
@julio-santiesteban : sorry, it is really hostpath and not hostdir. updated the description, you can find k8s reference there now.
